apiVersion: "kubeflow.org/v1alpha2"
kind: "TFJob"
metadata:
  name: "dist-mnist-with-mounts"
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: kubeflow/tf-dist-mnist-test:1.0
              volumeMounts:
              -	mountPath: "/tmp/mnist-data"
              	name: claim-tf
          volumes:
          	- name: claim-tf
          	  persistentVolumeClaim:
          	  	claimName: admin-tf-claim
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: kubeflow/tf-dist-mnist-test:1.0
              volumeMounts:
              -	mountPath: "/tmp/mnist-data"
              	name: claim-tf
          volumes:
          	- name: claim-tf
          	  persistentVolumeClaim:
          	  	claimName: admin-tf-claim
